name: Scheduled

on:
  push:
    branches: [master]

jobs:
  benchmark:
    strategy:
      matrix:
        case:
          - mwa-minimal
          - mwa-initial
          - mwa-arco-pro
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: npm install -g pnpm@^6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: wireit cache
        uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: cd scripts && pnpm install

      - name: Run benchmark
        run: cd scripts && GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm start -- ${{ matrix.case }}
